### ISSUE TITLE
The URL in the project description (`/untitled`) is not working

### ISSUE THREAD

**Issue by chauff** [mvallet91/edx-db#1]
Leads to a 404

**Comment by mvallet91** [comment]
Fixed in #10f3905afc0e83f4d06262f4a2fd92e405129864

**Comment by chauff** [comment]
Still an issue in the project description of the GitHub repo, the readme is now fixed.
